### ISSUE TITLE
path of the files when running the script

### ISSUE THREAD

**Issue by zeddo123** [LetMePy/Renommeur-de-fichiers#1]
how about adding the path of the files (in the **args**) when running the script

**Comment by RedN4ks** [comment]
Don't need to.
Bah justement, l'ingeniosité du machin c'est qu'il détecte lui même les noms qui correspondent pas au format. Pourquoi les spécifier soi-même ?

**Comment by zeddo123** [comment]
thanks for the quick response,
I suggested this because it would be (in my opinion) nice to let the script be in one place and then give him the folder to rename
like this: **python 000.py /home/picture**

**Comment by RedN4ks** [comment]
Okay i'll do that. it's indeed a nice idea.
